# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
